In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
hotel_df = pd.read_csv("weather_data/WeatherPy_vacation.csv")
hotel_df.head(20)

City_ID           City Country          Current Description  Max Temp  \
0         0         Atuona      PF                broken clouds     79.74   
1         2     The Valley      AI                   few clouds     82.99   
2        10           Gizo      SB              overcast clouds     83.75   
3        22       Zhuanghe      CN                    clear sky     77.72   
4        36        La Fria      VE                broken clouds     86.00   
5        41       Katsuura      JP  light intensity shower rain     84.00   
6        42        Paciran      ID                broken clouds     78.24   
7        44       Tessalit      ML                broken clouds     85.44   
8        45           Suba      PH              overcast clouds     84.72   
9        46          Kapaa      US              overcast clouds     84.20   
10       51  Saint Anthony      US                    clear sky     84.20   
11       63      Hithadhoo      MV              overcast clouds     83.43   
12       68  Cockburn Town      TC                broken clouds     84.20   
13       71           Naze      JP                broken clouds     84.20   
14       75           Hilo      US                broken clouds     84.20   
15       76      Flagstaff      US                    clear sky     90.00   
16       83       Victoria      HK              overcast clouds     88.00   
17       84    Mitsamiouli      KM                    clear sky     76.93   
18       88          Avera      US                    clear sky     86.00   
19       91       Hamilton      US                broken clouds     82.40   

      Lat     Lng                                 Hotel Name  
0   -9.80 -139.03                                Villa Enata  
1   18.22  -63.06               CeBlue Villas & Beach Resort  
2   -8.10  156.84                         Imagination Island  
3   39.70  122.99  Hanting Express Dalian Zhuanghe Qiansheng  
4    8.22  -72.24            Estacionamiento de los toledos.  
5   35.13  140.30                    Katsuura Hotel Mikazuki  
6   -6.88  112.38                 Tanjung Kodok Beach Resort  
7   20.20    1.01                                        NaN  
8   10.84  121.01                        Suba Pensione House  
9   22.08 -159.32     Sheraton Kauai Resort at Coconut Beach  
10  45.02  -93.22     Holiday Inn Express Roseville-St. Paul  
11  -0.60   73.08                          Scoop Guest House  
12  21.46  -71.14                         Osprey Beach Hotel  
13  28.37  129.48                                奄美ポートタワーホテル  
14  19.73 -155.09                        Hilo Hawaiian Hotel  
15  35.20 -111.65               Drury Inn & Suites Flagstaff  
16  22.29  114.16                         Mini Hotel Central  
17 -11.38   43.28                                  Foyer ADM  
18  33.19  -82.53                                        NaN  
19  39.18  -84.53                  Six Acres Bed & Breakfast

In [3]:
#Create separate DataFrames for each city on the travel route
clarksville_df = hotel_df.loc[hotel_df["City"] == "Clarksville"]
saint_anthony_df = hotel_df.loc[hotel_df["City"] == "Saint Anthony"]
sturgeon_bay_df = hotel_df.loc[hotel_df["City"] == "Sturgeon Bay"]
evanston_df = hotel_df.loc[hotel_df["City"] == "Evanston"]

In [4]:
clarksvilleTup = ()
clarksvilleTup = clarksville_df.to_numpy()[0][5:7]

array([36.53, -87.36], dtype=object)

In [5]:
evanstonTup = ()
evanstonTup = evanston_df.to_numpy()[0][5:7]

array([42.04, -87.69], dtype=object)

In [6]:
sturgeon_bayTup = ()
sturgeon_bayTup = sturgeon_bay_df.to_numpy()[0][5:7]

'AIzaSyBvAnhDUb0FqXHCMgdgLC5wlCg826OapNI'

In [7]:
saint_anthonyTup = () 
saint_anthonyTup = saint_anthony_df.to_numpy()[0][5:7]

array([45.02, -93.22], dtype=object)

In [9]:
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

# Latitude-longitude pairs
clarksville = clarksvilleTup
evanston = evanstonTup
sturgeon_bay = sturgeon_bayTup
saint_anthony = saint_anthonyTup

fig = gmaps.figure()
vacay_iten = gmaps.directions_layer(clarksville, saint_anthony, waypoints=[evanston, sturgeon_bay], travel_mode='BICYCLING')
fig.add_layer(vacay_iten)
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Concatenate DFs
frames = [clarksville_df, saint_anthony_df, sturgeon_bay_df, evanston_df]
vacay_itenDF = pd.concat(frames).reset_index()
vacay_itenDF

index  City_ID           City Country Current Description  Max Temp    Lat  \
0    148      545    Clarksville      US          few clouds     86.00  36.53   
1     10       51  Saint Anthony      US           clear sky     84.20  45.02   
2    153      563   Sturgeon Bay      US           clear sky     80.60  44.83   
3    121      468       Evanston      US    scattered clouds     82.99  42.04   

     Lng                                      Hotel Name  
0 -87.36                           Westgate Inn & Suites  
1 -93.22          Holiday Inn Express Roseville-St. Paul  
2 -87.38               AmericInn by Wyndham Sturgeon Bay  
3 -87.69  Hilton Garden Inn Chicago North Shore/Evanston

In [25]:
# Add a pop-up marker for each city.
locations = vacay_itenDF[["Lat", "Lng"]]
fig = gmaps.figure(center=(41.5, -90.4), zoom_level=4)
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}, {Max Temp}°F</dd>
</dl>
"""
# Store the DataFrame Row.
iten_info = [info_box_template.format(**row) for index, row in vacay_itenDF.iterrows()]

marker_layer = gmaps.marker_layer(locations, info_box_content=iten_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))